# -*- coding: utf-8 -*-
"""Agentic AI Email Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHoVVU1KmCTEskgjaFhdNoz4i45MRezI

**This project is an agentic AI that automatically reads incoming emails and generates professional, context-aware replies based on the email content.**
"""

!pip install torch transformers ipywidgets accelerate

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import ipywidgets as widgets
from IPython.display import display, clear_output

# Load model
model_id = "Qwen/Qwen2.5-1.5B-Instruct"
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
).to(device)

def email_agent(email_text: str, user_name: str = "User") -> str:
    """
    Generates a professional, concise, context-aware reply to an email.
    """
    prompt = f"""
You are an AI email assistant. Write a clear, professional, and polite reply
to the following email. Include the sender's name or company if mentioned.
The user's name should appear only at the end.

Incoming email:
\"\"\"{email_text}\"\"\"

Reply:
"""
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=250,
        do_sample=True,  # allow creative, context-aware responses
        temperature=0.7,
        repetition_penalty=1.2,
        no_repeat_ngram_size=3,
        eos_token_id=tokenizer.eos_token_id,
    )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "Reply:" in decoded:
        decoded = decoded.split("Reply:", 1)[1].strip()
    if user_name not in decoded:
        decoded += f"\n\nBest regards,\n{user_name}"
    return decoded.strip()

# -------------------------------
# GUI Chatbot for Email Responses
# -------------------------------
print("Welcome to your AI Email Assistant!")

name_input = widgets.Text(
    description="Your name:",
    placeholder="Enter your name"
)
email_input = widgets.Textarea(
    description="Incoming email:",
    placeholder="Paste or type the email here",
    layout=widgets.Layout(width='80%', height='100px')
)
reply_output = widgets.Output()
send_button = widgets.Button(description="Generate Reply", button_style='success')

def on_button_click(b):
    clear_output(wait=True)
    display(name_input, email_input, send_button, reply_output)
    with reply_output:
        user_name = name_input.value.strip() or "User"
        email_text = email_input.value.strip()
        if email_text:
            print("--- AI Generated Reply ---\n")
            reply = email_agent(email_text, user_name=user_name)
            print(reply)
            print("\n--------------------------\n")
        else:
            print("Please enter an email to generate a reply.")

send_button.on_click(on_button_click)
display(name_input, email_input, send_button, reply_output)